config/routes.rb
Rails.application.routes.draw do

  resources :tags
  resources :experts
  root to: 'static_pages#home'

  get '/:id' => "shortener/shortened_urls#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expert.rb
class Expert < ApplicationRecord
  #has_shortened_urls
  has_many :tags, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, :source => :expert

  after_destroy do |f|
    if Friendship.where(:expert_id => f.friend_id, :friend_id => f.expert_id).present?
      Friendship.destroy(:expert_id => f.friend_id, :friend_id => f.expert_id)
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :expert, :foreign_key => :friend_id

  after_save do |f|
    # Friendships records are created with expert_id and friend_id
    # After save, create another record between friend_id and expert_id

    # Make sure than a relationship between the two friends doesn't already exist.
    unless Friendship.where(:expert_id => f.friend_id, :friend_id => f.expert_id).present?
      Friendship.create!(:expert_id => f.friend_id, :friend_id => f.expert_id)
    end
  end

  # Look for the inverse expert object and remove as a friend.
  after_destroy do |f|
    #inverse = Friendship.find(:first, :conditions => {:friend_id => f.expert_id})
    if Friendship.where(:expert_id => f.friend_id, :friend_id => f.expert_id).present?
      Friendship.destroy!(:expert_id => f.friend_id, :friend_id => f.expert_id)
    end
  end

  # ORM Notes
  # expert.friends returns an array of friends.
  # expert.friendship returns details about a specific relationship.

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :expert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Needed for nokogiri.
  require 'open-uri'

  def shortener_generate_url(url)
    Shortener::ShortenedUrl.generate(url) # Called during create but after save.
  end

  # Get all of the heading tags from the provided URL. Save them to the tags table.
  def set_heading_tags(url)

    html = URI.open(url)
    parsed_data = Nokogiri::HTML.parse(html)

    heading_one_tags = parsed_data.xpath("//h1")
    heading_one_tags.each do |tag|
      @expert.tags.create(tag: "h1", url: "#{tag.text}")
    end

    heading_two_tags = parsed_data.xpath("//h2")
    heading_two_tags.each do |tag|
      @expert.tags.create(tag: "h2", url: "#{tag.text}")
    end

    heading_three_tags = parsed_data.xpath("//h3")
    heading_three_tags.each do |tag|
      @expert.tags.create(tag: "h3", url: "#{tag.text}")
    end
  end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  before_action :set_expert, only: [:show, :edit, :update, :destroy]

  # GET /experts
  # GET /experts.json
  def index
    @experts = Expert.all
  end

  # GET /experts/1
  # GET /experts/1.json
  def show
    @tags = @expert.tags.all
    @friends = @expert.friends
    @friends_count = @expert.friends.count
  end

  # GET /experts/new
  def new
    @expert = Expert.new
  end

  # GET /experts/1/edit
  def edit
  end

  # POST /experts
  # POST /experts.json
  def create
    @expert = Expert.new(expert_params)

    respond_to do |format|
      if @expert.save
        format.html { redirect_to @expert, notice: 'Expert was successfully created.' }
        format.json { render :show, status: :created, location: @expert }

        # Called during the create action, after save. (As indicated by challenge.)
        set_heading_tags(@expert.url)
        shortener_generate_url(@expert.url)
      else
        format.html { render :new }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experts/1
  # PATCH/PUT /experts/1.json
  def update
    respond_to do |format|
      if @expert.update(expert_params)
        format.html { redirect_to @expert, notice: 'Expert was successfully updated.' }
        format.json { render :show, status: :ok, location: @expert }
      else
        format.html { render :edit }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experts/1
  # DELETE /experts/1.json
  def destroy
    @expert.destroy
    respond_to do |format|
      format.html { redirect_to experts_url, notice: 'Expert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expert
      @expert = Expert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expert_params
      params.require(:expert).permit(:name, :url)
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:tag, :url, :expert_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/experts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@expert) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :url

  .form-actions
    = f.button :submit

app/views/experts/edit.html.haml
%h1 Editing expert

= render 'form'

= link_to 'Show', @expert
\|
= link_to 'Back', experts_path

app/views/experts/index.html.haml
%h1 Experts List

%table.table
  %thead
    %tr
      %th Name
      %th Shortened Url
      %th
      %th
      %th

  %tbody
    - @experts.each do |expert|
      %tr
        %td= expert.name
        %td= short_url(expert.url)
        %td= link_to 'Show', expert
        %td= link_to 'Edit', edit_expert_path(expert)
        %td= link_to 'Destroy', expert, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to new_expert_path do
  .btn.btn-primary New Expert

app/views/experts/new.html.haml
%h1 New expert

= render 'form'

= link_to 'Back', experts_path

app/views/experts/show.html.haml
%p#notice= notice

.card
  .card-header
    Profile
  .card-body

    %h5.card-title
      = @expert.name
    Short URL:
    = link_to short_url(@expert.url)
    %br
    Long URL:
    = link_to @expert.url

    %hr
    %h5= "Friends: " + @friends_count.to_s
    - @friends.each do |friend|
      = link_to friend.name, expert_path(friend.id)

    %hr
    %h5 Heading Tags

    %table.table
      %thead
        %tr
          %th Tag
          %th URL
          %th

      %tbody
        - @tags.each do |tag|
          %tr
            %td= tag.tag
            %td= tag.url
            %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }

  .card-footer
    = link_to experts_path do
      .btn.btn-primary Back

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "Greenwave Challenge", root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        = link_to "Home", root_path, class: "nav-link"
      %li.nav-item
        = link_to "Experts", experts_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GreenwaveChallenge
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/nav"
    .container
      .row
        .col-lg-12
          = yield

app/views/static_pages/home.html.haml
%h1 Greenwave Challenge Application
%p This application was built for the Greenwave challenge by Aaron S. 

app/views/tags/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@tag) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :tag
    = f.input :url
    = f.association :expert

  .form-actions
    = f.button :submit

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%h1 Listing tags

%table
  %thead
    %tr
      %th Tag
      %th Url
      %th Expert
      %th
      %th
      %th

  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.tag
        %td= tag.url
        %td= tag.expert
        %td= link_to 'Show', tag
        %td= link_to 'Edit', edit_tag_path(tag)
        %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
%p#notice= notice

%p
  %b Tag:
  = @tag.tag
%p
  %b Url:
  = @tag.url
%p
  %b Expert:
  = @tag.expert

= link_to 'Edit', edit_tag_path(@tag)
\|
= link_to 'Back', tags_path